---
title: "Allen Bush-Beaupré"
---

::: lang-toggle
<button class="lang-toggle-btn active" data-lang="en">

English

</button>

<button class="lang-toggle-btn" data-lang="fr">

Français

</button>
:::

:::: lang-en
::: lang-en
## Welcome

I am a research scientist at [Université de Sherbrooke](https://www.usherbrooke.ca/) and [Bishop's University](https://www.ubishops.ca/), Sherbrooke, QC, CAN. During my MSc (2020-22), I developed an interest for quantitative methods that I now have the privilege to use in the different roles that I occupy.

I study agricultural entomology with a focus on integrated pest management through a better understanding of insects' ecology. My work in [Jade Savage](https://qcbs.ca/member/?profile=57)'s lab (Bishop's University) is on the Delia project, studying root maggots (*Delia spp.* (Diptera : Anthomyiidae)) in partnership with [PRISME/Phytodata](https://prisme.ca/) and their [sterile fly program](https://prisme.ca/achat-de-mouches-steriles/). My work in [Marc Bélisle](https://www.cef-cfr.ca/pmwiki.php?n=Membres.MarcBelisle)'s lab (Université de Sherbrooke) is about applying statistical methods to the different projects going on in the lab (Tree Swallows and their ectoparasites, plant and insect phenology, Lepidoptera inventories, pesticide contamination levels). My main project for this role, however, is on a project involving integrated pest management in lettuce crops ([click here](https://www.youtube.com/watch?v=xSJ8RlIjBXE&list=PLp-PVpJeuCjQq1MFk6Oh3_65q8jhgn3xr) to see our recent scientific mission in Europe).

As of 2026, I am also tasked to assist the members of the Centre de Recherche en Écologie de l'Université de Sherbrooke ([CREUS](https://creus-recherche.weebly.com/)) with their statistical analyses. During these consultations, I will inevitably be learning new methods and making various tutorials. These will be available on [my blog](posts.html). If you are a CREUS member and would like to book a consultation with me, please follow the instructions on the [Consultations CREUS](consultation.html) page.
:::
::::

::: lang-fr
## Bienvenue {.lang-fr}

Je suis professionnel de recherche à l'[Université de Sherbrooke](https://www.usherbrooke.ca/) et à l'[Université Bishop's](https://www.ubishops.ca/), Sherbrooke, QC, CAN. Durant ma maîtrise (2020-22), j'ai développé un intérêt pour les méthodes quantitatives que j'ai maintenant le privilège d'utiliser dans les différents rôles que j'occupe.

J'étudie l'entomologie agricole avec un focus sur la lutte intégrée par une meilleure compréhension de l'écologie des insectes. Mon travail dans le laboratoire de [Jade Savage](https://qcbs.ca/member/?profile=57) (Université Bishop's) porte sur le projet Delia, étudiant les mouches des racines (*Delia spp.* (Diptera : Anthomyiidae)) en partenariat avec [PRISME/Phytodata](https://prisme.ca/) et leur [programme de mouches stériles](https://prisme.ca/achat-de-mouches-steriles/). Mon travail dans le laboratoire de [Marc Bélisle](https://www.cef-cfr.ca/pmwiki.php?n=Membres.MarcBelisle) (Université de Sherbrooke) consiste à appliquer des méthodes statistiques aux différents projets en cours dans le laboratoire (hirondelles bicolores et leurs ectoparasites, phénologie des plantes et des insectes, inventaires de Lépidoptères, niveaux de contamination par les pesticides). Mon projet principal pour ce rôle, cependant, porte sur un projet impliquant la lutte intégrée dans les cultures de laitue ([cliquez ici](https://www.youtube.com/watch?v=xSJ8RlIjBXE&list=PLp-PVpJeuCjQq1MFk6Oh3_65q8jhgn3xr) pour voir notre récente mission scientifique en Europe).

Depuis 2026, je suis également chargé d'assister les membres du Centre de Recherche en Écologie de l'Université de Sherbrooke ([CREUS](https://creus-recherche.weebly.com/)) avec leurs analyses statistiques. Durant ces consultations, j'apprendrai inévitablement de nouvelles méthodes et créerai divers tutoriels. Ceux-ci seront disponibles sur [mon blog](posts.html). Si vous êtes membre du CREUS et souhaitez réserver une consultation avec moi, veuillez suivre les instructions sur la page [Consultations CREUS](consultation.html).
:::

------------------------------------------------------------------------

::: {style="margin-top: 5rem;"}
:::

:::: lang-en
::: lang-en
## Use of Large Language Models

I use large language models as a programming assistant to create this website and the templates for the tutorials and blog posts. All scientific material associated to my name is Human Generated, however.
:::
::::

::: lang-fr
## Utilisation des grands modèles de langage {.lang-fr}

J'utilise les grands modèles de langage comme assistant de programmation pour créer ce site Web et les gabarits pour les tutoriels et les articles de blog. Tout le matériel scientifique associé à mon nom est cependant généré par un humain.
:::

------------------------------------------------------------------------

```{=html}
<script>
// Language toggle functionality
document.addEventListener('DOMContentLoaded', function() {
  let currentLang = localStorage.getItem('language') || 'en';
  setLanguage(currentLang);
  
  document.querySelectorAll('.lang-toggle-btn').forEach(btn => {
    btn.addEventListener('click', function() {
      const lang = this.dataset.lang;
      setLanguage(lang);
      localStorage.setItem('language', lang);
    });
  });
});

function setLanguage(lang) {
  // Hide all language content
  document.querySelectorAll('.lang-en, .lang-fr').forEach(el => {
    el.style.display = 'none';
  });
  
  // Show selected language content
  document.querySelectorAll('.lang-' + lang).forEach(el => {
    el.style.display = 'block';
  });
  
  // Update active button state
  document.querySelectorAll('.lang-toggle-btn').forEach(btn => {
    btn.classList.remove('active');
    if (btn.dataset.lang === lang) {
      btn.classList.add('active');
    }
  });
  
  // Update TOC if present
  setTimeout(() => filterTOC(lang), 100);
  setTimeout(() => filterTOC(lang), 500);
  setTimeout(() => filterTOC(lang), 1000);
}

function filterTOC(lang) {
  const tocItems = document.querySelectorAll('#TOC li');
  
  tocItems.forEach(li => {
    const link = li.querySelector('a');
    if (!link) return;
    
    const href = link.getAttribute('href') || '';
    
    const frenchSections = ['bienvenue', 'un-peu-à-propos-de-moi'];
    const englishSections = ['welcome', 'a-bit-about-me'];
    
    const isFrench = frenchSections.some(section => href.includes(section));
    const isEnglish = englishSections.some(section => href.includes(section));
    
    if (lang === 'en' && isFrench) {
      li.style.display = 'none';
    } else if (lang === 'fr' && isEnglish) {
      li.style.display = 'none';
    } else {
      li.style.display = '';
    }
  });
}
</script>
```